name: daily-email

on:
  # schedule:
  #   - cron: '*/5 * * * *'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          server_address: smtp.gmail.com
          server_port: 465
          python-version: 3.x
      - name: Install dependencies
        run: pip install -r requirements.txt
      # - name: Load dotenv file
      #   run: |
      #     python -c "from dotenv import load_dotenv; load_dotenv()"
      - name: Run email script
        env:
          EMAIL: ${{secrets.EMAIL}}
          PASSWORD: ${{secrets.PASSWORD}}
        run: python main.py
